AWSTemplateFormatVersion: 2010-09-09
Description: Create S3Bucket using cloudformation
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label: 
        default: "S3 Bucket"
      Parameters: 
        - S3Bucket

Parameters:
  S3BucketName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
    Default: s3bucket9932
    Description: Give your S3Bucket name
    MaxLength: 64
    MinLength: 8
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  S3Bucket:
    Description: S3Bucket Created using this template.
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-S3Bucket